# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d816943eaf3ab4c83ab717f67918089dadc3f6655e926bd4423163a9f370b126161382a9b139236e85fc0e22d198d9c08166d14303c0e3280097edc341bffd45

test:
  secret_key_base: aff2d73c696c253f08914300b1bd284580366a5996d138be0c4cca3a876126eb532644db52ffd4e570210ba4bf49c9588f535a9e1b79dd4373c516e88361d0ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
